# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/agricola_db
spring.datasource.username=postgres
spring.datasource.password=admin

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Puerto del servidor
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=INFO